model_args:
  model_name_or_path: 'klue/bert-base'
  dense_train_model_name: 'klue/bert-base' # DPR Encoder model name 추가
  p_encoder_path: './saved_models/p_encoder'
  q_encoder_path: './saved_models/q_encoder'
  config_name: 
  tokenizer_name:

data_args:
  dataset_name: '../../dataset/train_dataset'
  train_dataset_name: '../../dataset/train_dataset/train'
  valid_dataset_name: '../../dataset/train_dataset/validation'
  dataset: 'basic' # basic , korquad, both
  wiki_data_path: '../../dataset/wikipedia_documents.json'
  setting_path: '../retrieval/setting.json'

# DPR model training args # lr, batch_size, epochs, weight_decay, gradient
training_args:
  learning_rate: 2e-5
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs : 10
  weight_decay: 0.01
  gradient_accumulation_steps: 1
  warmup_ratio : 0.1

  save_total_limit : 2
  do_train : True

  p_encoder_save_name : 'saved_model_name'
  q_encoder_save_name : 'saved_model_name'
  
  # Dense Passage Retriver arguments
  in_batch_neg : True
  num_neg : 3 # 2^n - 1
  hard_neg : False