model_args:
  model_name_or_path : 'klue/bert-base'
  config_name:
  tokenizer_name:

train_args:
  dataset_name: '../dataset/train_dataset'
  overwrite_cache: False
  preprocessing_num_workers:
  max_seq_length: 384
  pad_to_max_length: False
  doc_stride: 128
  max_answer_length: 30
  eval_retrieval: True
  num_clusters: 64
  top_k_retrieval: 10
  retriever_type: 'faiss'  # base, faiss, elastic
  #use_faiss : False

retrieve_args:
  output_dir: './models'
  logging_dir: './logs'
  per_device_train_batch_size : 16
  per_device_eval_batch_size : 16
  save_total_limit : 2
  load_best_model_at_end : True
  num_train_epochs : 2
  eval_steps : 250
  evaluation_strategy : 'steps'
  overwrite_output_dir : True
  do_train : True
  do_eval : False # 이거 근데 False라고 박아놧는데 자꾸 True로 들어감.. 왜일까
  do_predict : False