model_args:
  model_name_or_path : 'klue/bert-base'
  config_name:
  tokenizer_name:

data_args:
  dataset_name: './dataset/test_dataset'
  overwrite_cache: False
  preprocessing_num_workers:
  max_seq_length: 384
  pad_to_max_length: False
  doc_stride: 128
  max_answer_length: 30
  eval_retrieval: True
  num_clusters: 64
  top_k_retrieval: 10
  use_faiss : False

training_args:
  output_dir: './models/train_dataset'
  logging_dir: './logs'
  per_device_train_batch_size : 16
  per_device_eval_batch_size : 16
  save_total_limit : 2
  load_best_model_at_end : True
  num_train_epochs : 1
  eval_steps : 250
  evaluation_strategy : 'steps'
  overwrite_output_dir : True
  do_train : False 
  do_eval : False 
  # do_eval 근데 False라고 박아놧는데 자꾸 True로 들어감.. 왜일까
  # evaluation strategy가 설정되어있으면 알아서 True로 들어간다고 함
  # 추후에 inference용 config 파일이 필요할듯
  do_predict : True