model_args:
  model_name_or_path : 'klue/bert-base'
  config_name:
  tokenizer_name:


rtv_args:
  top_k : 10
  context_path : 'wikipedia_documents.json'
  p_encoder_path : './dpr_model/p_encoder.pt'
  q_encoder_apth : './dpr_model/q_encoder.pt'

train_args:
  train_dataset : "../dataset/train_dataset/"
  output_dir: './dpr_model'
  per_device_train_batch_size : 16
  per_device_eval_batch_size : 16
  learning_rate: '3e-4'
  num_train_epochs : 40
  weight_decay : 0.01
  num_neg : 5